In [3]:
import numpy as np

____________
____________
**Exercício:** Crie em numpy a seguinte matriz:
$$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

In [33]:
# Resposta
array = np.array([[1, 2, 1], [3, 0, 1], [0, 2, 4]])
array

array([[1, 2, 1],
       [3, 0, 1],
       [0, 2, 4]])

In [34]:
print(array)

[[1 2 1]
 [3 0 1]
 [0 2 4]]


_______________
_______________

**Exercício:**
Sabendo que a operação de multiplicação é feita por __*__ , multiplique o vetor *a* por 2.

In [88]:
a*2

array([2, 4, 6, 8])

**Exercício:**
Sabendo que a operação de divisão é feita por __/__ , divida o vetor *a* por 2.

In [87]:
a/2

array([0.5, 1. , 1.5, 2. ])

**Exercício:**
Sabendo que a operação de potenciação é feita por __**__ , calcule o quadrado dos elementos do vetor *a*.

In [85]:
a2 = a**2
a2.dtype

dtype('int64')

In [89]:
a**2

array([ 1,  4,  9, 16])

_______________________
_______________________

**Exercício:** encontre a média e o desvio padrão da matriz, sabendo que os métodos são representados por `np.mean()` e `np.std()`, respectivamente.

In [12]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
media_matriz = np.mean(matriz)
#ou
media_matriz = matriz.mean()

std_matriz = matriz.std()

print(f'Média: {media_matriz:.2f} - Desvio Padrão: {std_matriz:.2f}')

Média: 3.50 - Desvio Padrão:1.71


operação realizada ao longo dos índices:

In [19]:
matriz.min(axis=1)

array([1, 4])

In [20]:
matriz.min(axis=0)

array([1, 2, 3])

_____________
_____________

**Exercício:** Realize a soma para cada linha e para cada coluna:

In [25]:
# linha
matriz.sum(axis=1)
#ou
matriz.sum(1)

array([ 6, 15])

In [23]:
# coluna
matriz.sum(axis=0)

array([5, 7, 9])

___________
___________


## Exercícios

1 - Selecione todos os valores ímpares do seguinte array:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [84]:
array = np.arange(1, 10)

In [85]:
array[array % 2 == 1]

array([1, 3, 5, 7, 9])

2 - Substitua os valores ímpares do seguinte array por 0:  <br>
array = [1, 2, 3, 4, 5, 6, 7, 8, 9] <br>


In [86]:
array[array % 2 == 1] = 0
array

array([0, 2, 0, 4, 0, 6, 0, 8, 0])

3 - Considere o dataset da iris disponível em: 
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'<br> 
Nesse dataset temos as seguintes informações:<br> 
   * Coluna 1. sepal length em cm<br> 
   * Coluna 2. sepal width em cm<br> 
   * Coluna 3. petal length em cm<br> 
   * Coluna 4. petal width em cm<br> 
   * Coluna 5. classe: 
                -- Iris Setosa 
                -- Iris Versicolour 
                -- Iris Virginica 
                
Utilizando o método `np.genfromtxt()`, importe as 4 primeiras colunas do dataset do íris e print as 10 primeiras linhas <br>

In [126]:
#ler dados
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [127]:
# print as 10 primeiras linhas
iris[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

4 - Calcule a média, mediana e desvio padrão da coluna sepallenght

In [129]:
sepal_length = iris[:, 0]

In [130]:
sepal_length = iris[:, 0]
media, mediana, desvio_padrao = np.mean(sepal_length), np.median(sepal_length), np.std(sepal_length)
print(f'Média: {media:.2f}, Mediana: {mediana:.2f}, Desvio Padrão: {desvio_padrao:.2f}')

Média: 5.84, Mediana: 5.80, Desvio Padrão: 0.83


5 - Filtre a matriz para conter apenas dados nos quais petallength (3ª coluna) > 1.5 e sepallength (1ª coluna) < 5.0

In [135]:
condicao = (iris[:, 2] > 1.5) & (iris[:, 0] < 5.0)
iris[condicao]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

6 - Esse dataset possui nans?

In [134]:
np.isnan(iris).sum()

0

7 - Crie uma coluna de volume sabendo que ele pode ser calculado por (pi x petallength x sepal_length^2)/3

In [151]:
# Solução
# Computa o volume
sepallength = iris[:, 0]
petallength = iris[:, 2]
volume = np.pi * petallength * (sepallength**2)/3

# Adiciona a segunda dimensão no vetor de volume
# volume = volume[:, np.newaxis]
volume = volume.reshape(-1,1)

# Adiciona o vetor volume como coluna da matriz original
out = np.hstack([iris, volume])

# View
out[:4]

array([[ 5.1       ,  3.5       ,  1.4       ,  0.2       , 38.13265163],
       [ 4.9       ,  3.        ,  1.4       ,  0.2       , 35.20049849],
       [ 4.7       ,  3.2       ,  1.3       ,  0.2       , 30.07237208],
       [ 4.6       ,  3.1       ,  1.5       ,  0.2       , 33.23805027]])